# Generated by Django 4.0.3 on 2023-01-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_rename_section_number_binvo_bin_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='location',
            new_name='bin',
        ),
    ]
